version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:prod-php-7.4-ubuntu20.04
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/apache2/cert:/etc/apache2/cert
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      ohrmprodnet:
        ipv4_address: 10.2.1.100
    privileged: true
    restart: always
    hostname: orangehrm-prod-web_ubuntu
    container_name: prod_web_ubuntu

networks:
  ohrmprodnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16
         gateway: 10.2.0.1
